name: 'dc_311_analytics'
version: '1.0.0'
config-version: 2

profile: 'dc_311'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dc_311_analytics:
    bronze:
      +materialized: view
    silver:
      +materialized: view
    gold:
      +materialized: table
